# Generated by Django 4.2.23 on 2025-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.BooleanField(default=True),
        ),
    ]
