# Generated by Django 4.2.23 on 2025-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
