# Generated by Django 4.2.23 on 2025-08-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0009_order_orderitem_customeraddress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_code",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
