import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import NavBarContainer from "@/components/navbar/NavBarContainer";


const ubuntu = Ubuntu({
  weight: ["400", "500", "700"], // Changed "600" to "700"
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shoppit - Building",
  description: "Generated by create next app",
  };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body className="">
        <main className="w-full">
          <NavBarContainer />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}